---
engines:
  csslint:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      overqualified-elements:
        enabled: false
  duplication:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths: []
