language: node_js
node_js:
    - "stable"

services:
    - postgresql
 
script:
    - npm test
before_script:
    - npm install


after_script: cat coverage/*lcov.info | ./node_modules/.bin/coveralls 