// user
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESSFUL = 'SIGN_UP_SUCCESSFUL';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAIL = 'LOGIN_FAIL';

// admin
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESSFUL = 'UPDATE_USER_SUCCESSFUL';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESSFUL = 'FETCH_USERS_SUCCESSFUL';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESSFUL = 'DELETE_USER_SUCCESSFUL';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

export const CREATE_ROLE_REQUEST = 'CREATE_ROLE_REQUEST';
export const CREATE_ROLE_SUCCESSFUL = 'CREATE_ROLE_SUCCESSFUL';
export const CREATE_ROLE_FAIL = 'CREATE_ROLE_FAIL';

export const FETCH_ROLE_REQUEST = 'FETCH_ROLE_REQUEST';
export const FETCH_ROLE_SUCCESSFUL = 'FETCH_ROLE_SUCCESSFUL';
export const FETCH_ROLE_FAIL = 'FETCH_ROLE_FAIL';

export const SEARCH_USER_REQUEST = 'SEARCH_USER_REQUEST';
export const SEARCH_USER_SUCCESSFUL = 'SEARCH_USER_SUCCESSFUL';
export const SEARCH_USER_FAIL = 'SEARCH_USER_FAIL';

export const SEARCH_DOCUMENT_REQUEST = 'SEARCH_DOCUMENT_REQUEST';
export const SEARCH_DOCUMENT_SUCCESSFUL = 'SEARCH_DOCUMENT_SUCCESSFUL';
export const SEARCH_DOCUMENT_FAIL = 'SEARCH_DOCUMENT_FAIL';

// document
export const CREATE_DOCUMENT_REQUEST = 'CREATE_DOCUMENT_REQUEST';
export const CREATE_DOCUMENT_SUCCESSFUL = 'CREATE_DOCUMENT_SUCCESSFUL';
export const CREATE_DOCUMENT_FAIL = 'CREATE_DOCUMENT_FAIL';

export const FETCH_DOCUMENT_REQUEST = 'FETCH_DOCUMENT_REQUEST';
export const FETCH_DOCUMENT_SUCCESSFUL = 'FETCH_DOCUMENT_SUCCESSFUL';
export const FETCH_DOCUMENT_FAIL = 'FETCH_DOCUMENT_FAIL';

export const UPDATE_DOCUMENT_REQUEST = 'UPDATE_DOCUMENT_REQUEST';
export const UPDATE_DOCUMENT_SUCCESSFUL = 'UPDATE_DOCUMENT_SUCCESSFUL';
export const UPDATE_DOCUMENT_FAIL = 'UPDATE_DOCUMENT_FAIL';


export const DELETE_DOCUMENT_REQUEST = 'DELETE_DOCUMENT_REQUEST';
export const DELETE_DOCUMENT_SUCCESSFUL = 'DELETE_DOCUMENT_SUCCESSFUL';
export const DELETE_DOCUMENT_FAIL = 'DELETE_DOCUMENT_FAIL';
